apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc
  namespace: default
spec:
  selector:
    matchLabels:
      app: auth-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-svc
    spec:
      containers:
        - name: auth-svc
          image: 578965/forum-auth-service:master-fb0ab91
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: app-port
          livenessProbe:
            httpGet:
              path: /
              port: app-port
          readinessProbe:
            httpGet:
              path: /
              port: app-port
          resources:
            requests:
              memory: "150Mi"
              cpu: "150m"
            limits:
              memory: "300Mi"
              cpu: "300m"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc-svc
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: app-port
  selector:
    app: auth-svc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-svc-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /auth-svc(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-svc-svc
                port:
                  number: 80