apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forum-app-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:toufiq-austcse/forum-app.git
    targetRevision: HEAD
    path: deployments
  destination:
    server: https://kubernetes.default.svc
    namespace: forum-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
---
apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:toufiq-austcse/forum-app.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACBWYCBd0s6cNFen62ZT8eABfJvcKUvZ7wsa6WV0u3IO3wAAAJA270nHNu9J
    xwAAAAtzc2gtZWQyNTUxOQAAACBWYCBd0s6cNFen62ZT8eABfJvcKUvZ7wsa6WV0u3IO3w
    AAAEAMKLJfTn1/Y4SsKIXnOQTS+310t6w7nFXuqZXA7pI5+VZgIF3Szpw0V6frZlPx4AF8
    m9wpS9nvCxrpZXS7cg7fAAAABmFyZ29jZAECAwQFBgc=
    -----END OPENSSH PRIVATE KEY-----