apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forum-app-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/toufiq-austcse/forum-app.git
    targetRevision: HEAD
    path: deployments
  destination:
    server: https://kubernetes.default.svc
    namespace: forum-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
