version: "3"
services:
  auth-service:
    build: .
    hostname: auth-svc
    image: auth-svc
    container_name: auth-svc
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=$PORT
    ports:
      - $PORT:$PORT