version: "3"
services:
  post-service:
    build: .
    hostname: post-svc
    image: post-svc
    container_name: post-svc
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=$PORT
    ports:
      - $PORT:$PORT