name: Build and publish docker image
on:
  push:
    branches:
      - master
jobs:
  build-image:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Tag
        id: get_tag
        run: echo "::set-output name=short_ref::${GITHUB_REF#refs/heads/}-$(git rev-parse --short HEAD)"

      - name: Auth Service Build
        uses: docker/build-push-action@v3
        with:
          context: ./be/auth-service
          file: ./be/auth-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{secrets.SERVICE_NAME_PREFIX}}-auth-service:${{steps.get_tag.outputs.short_ref}}