name: Build and publish docker image
on:
  push:
    branches:
      - master
jobs:
  setup-build-publish:
    name: Setup, Build, and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get tag
        id: get_tag
        run: echo "::set-output name=short_ref::${GITHUB_REF#refs/heads/}-$(git rev-parse --short HEAD)"

      - name: Auth service build and push to registry
        uses: docker/build-push-action@v3
        with:
          context: ./be/auth-service
          file: ./be/auth-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{secrets.SERVICE_NAME_PREFIX}}-auth-service:${{steps.get_tag.outputs.short_ref}}

      - name: Post service build and push to registry
        uses: docker/build-push-action@v3
        with:
          context: ./be/post-service
          file: ./be/post-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{secrets.SERVICE_NAME_PREFIX}}-post-service:${{steps.get_tag.outputs.short_ref}}