name: Build and publish docker image
on:
  push:
    branches:
      - master
jobs:
  build-image:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run:
          echo "DOCKER_PASSWORD=$DOCKER_PASSWORD" >> $GITHUB_ENV


      - name: Auth Service Build
        uses: docker/build-push-action@v3
        with:
          context: ./be/auth-service
          file: ./be/auth-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/auth-service:latest